package bitkub

const (
	_API_STATUS                   = "/api/status"
	_API_SERVERTIME               = "/api/servertime"
	_API_MARKET_SYMBOLS           = "/api/market/symbols"
	_API_MARKET_TICKER            = "/api/market/ticker"
	_API_MARKET_TRADES            = "/api/market/trades"
	_API_MARKET_BIDS              = "/api/market/bids"
	_API_MARKET_ASKS              = "/api/market/asks"
	_API_MARKET_BOOKS             = "/api/market/books"
	_API_MARKET_DEPTH             = "/api/market/depth"
	_API_TRADINGVIEW              = "/tradingview/history"
	_API_MARKET_WALLET            = "/api/market/wallet"
	_API_MARKET_BALANCES          = "/api/market/balances"
	_API_MARKET_PLACE_BID         = "/api/market/place-bid"
	_API_MARKET_PLACE_ASK         = "/api/market/place-ask"
	_API_MARKET_PLACE_BID_TEST    = "/api/market/place-bid/test"
	_API_MARKET_PLACE_ASK_TEST    = "/api/market/place-ask/test"
	_API_MARKET_PLACE_ASK_BY_FIAT = "/api/market/place-ask-by-fiat"
	_API_MARKET_CANCEL_ORDER      = "/api/market/cancel-order"
	_API_MARKET_MY_OPEN_ORDERS    = "/api/market/my-open-orders"
	_API_MARKET_MY_ORDER_HISTORY  = "/api/market/my-order-history"
	_API_MARKET_ORDER_INFO        = "/api/market/order-info"
	_API_CRYPTO_ADDRESSES         = "/api/crypto/addresses"
	_API_CRYPTO_WITHDRAW          = "/api/crypto/withdraw"
	_API_CRYPTO_INTERNAL_WITHDRAW = "/api/crypto/internal-withdraw"
	_API_CRYPTO_DEPOSIT_HISTORY   = "/api/crypto/deposit-history"
	_API_CRYPTO_WITHDRAW_HISTORY  = "/api/crypto/withdraw-history"
	_API_CRYPTO_GENERATE_ADDRESS  = "/api/crypto/generate-address"
	_API_FIAT_ACCOUNTS            = "/api/fiat/accounts"
	_API_FIAT_WITHDRAW            = "/api/fiat/withdraw"
	_API_FIAT_DEPOSIT_HISTORY     = "/api/fiat/deposit-history"
	_API_FIAT_WITHDRAW_HISTORY    = "/api/fiat/withdraw-history"
	_API_MARKET_WSTOKEN           = "/api/market/wstoken"
	_API_USER_LIMIT               = "/api/user/limits"
	_API_USER_TRADING             = "/api/user/trading-credits"
)
